apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: U1BSSU5HX0RBVEFTT1VSQ0VfVVJM #jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  SPRING_DATASOURCE_USERNAME: U1BSSU5HX0RBVEFTT1VSQ0VfVVNFUk5BTUU= #callicoder
  SPRING_DATASOURCE_PASSWORD: U1BSSU5HX0RBVEFTT1VSQ0VfUEFTU1dPUkQ= #callicoder 
