apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: igorkuz/frontend:1.0 
        ports:
        - containerPort: 8080 #3000
        env:  
        - name: Backend_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: backend-url

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080 #3000
      targetPort: 8080 #3000
      nodePort: 30100