apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-frontend
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: igorkuz/frontend:1.0 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80 
        resources:
          limits:
            cpu: 0.2
            memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP #http?
      port: 80
      targetPort: 80 
      # nodePort: 30100